version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet pack -c release src/ConductorDotnetClient/ConductorDotnetClient.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '**\*.nupkg' 
   name: Package
   type: NuGetPackage
clone_depth: 1
on_finish :
  # any cleanup in here
deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: Kw8t/0aaUThr3JSA2krJut3gFuK4EHbF/qdsrp2Fhwm1bGchu3mUIxtgqtXoEY3C
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
